apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: gcp-bucket-sa
            secret:
              secretName: gcs-key
          containers:
          - name: mongo-backup
            image: k4mrul/gke-mongo-backup
            volumeMounts:
            - name: gcp-bucket-sa
              mountPath: /var/secrets/google
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/gcp_service_account.json
            - name:  MONGO_HOST
              value: <MONGO_HOST>
            - name:  MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-standalone-secrets
                  key: mongo-username
            - name:  MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-standalone-secrets
                  key: mongo-password
            - name:  BUCKET_NAME
              value: dokan-dev
          restartPolicy: OnFailure